CREATE PROCEDURE pr_GetPaymentByID @PAYMENTID INT
AS
	BEGIN
		SELECT * FROM Payments WHERE Id = @PAYMENTID;
	END
GO

CREATE PROCEDURE pr_GetPaymentsOfUser @USERID NVARCHAR(50)
AS
	BEGIN
		SELECT * FROM Payments WHERE UserId = @USERID;
	END
GO

CREATE PROCEDURE pr_UpdatePayment 
@PAYMENTID INT, 
@AMOUNT FLOAT, 
@ISPAID BIT
AS
	BEGIN
		UPDATE Payments
		SET
		Amount = COALESCE(@AMOUNT, Amount),
		IsPaid = COALESCE(@ISPAID, IsPaid)
		WHERE Id = @PAYMENTID;
	END
GO